合并master分支，修复冲突

diff --git a/bcs-ops/k8s/install_containerd b/bcs-ops/k8s/install_containerd
--- a/bcs-ops/k8s/install_containerd
+++ b/bcs-ops/k8s/install_containerd
@@ -23,7 +23,7 @@ safe_source() {
     #shellcheck source=/dev/null
     source "${source_file}"
   else
-    echo "[ERROR]: FAIL to source, missing ${source_file}"
+    echo "[ERROR]: FAIL to source, missing ${source_file}" >&2
     exit 1
   fi
   return 0
@@ -39,8 +39,15 @@ _yum_containerd() {
     curl -fsSL "$yum_repo" \
       | sed "s#https://download.docker.com#${MIRROR_URL}/docker-ce#g" \
       | tee "${repo_file}"
-    [[ ! -f /etc/tlinux-release ]] \
-      || sed -i "s/\$releasever/7/g" "$ROOT_DIR/docker-ce.repo"
+    if [[ -f /etc/tlinux-release ]];then
+      if grep "TencentOS Server 3.[0-9]*" /etc/tlinux-release;then
+        sed -i "s/\$releasever/8/g" "$ROOT_DIR/docker-ce.repo"
+      elif grep "TencentOS Server 2.[0-9]*" /etc/tlinux-release;then
+        sed -i "s/\$releasever/7/g" "$ROOT_DIR/docker-ce.repo"
+      elif grep "Tencent tlinux release 2.[0-9]*" /etc/tlinux-release;then
+        sed -i "s/\$releasever/7/g" "$ROOT_DIR/docker-ce.repo"
+      fi
+    fi
   else
     yum_repo="https://download.docker.com/linux/centos/docker-ce.repo"
     curl -fsSL "$yum_repo" -O "${repo_file}"
@@ -104,7 +111,7 @@ _offline_containerd() {
   if [[ -z ${tar_name} ]]; then
     utils::log "FATAL" "can't find docker installation package in ${bin_path}"
   else
-    tar xvzf "${tar_name}" -C /usr/bin/ --strip-components=1 bin/
+    tar xvzf "${tar_name}" -C /usr/local/bin/ --strip-components=1 bin/
     tar xvzf "${tar_name}" -C /etc/systemd/system/ --strip-components=1 systemd/
   fi
 
@@ -234,9 +241,11 @@ main() {
   test_img_url=${BK_PUBLIC_REPO:-"docker.io"}/library/hello-world:latest
   utils::log "DEBUG" "hello-world: ${test_img_url}"
 
-  if ! (ctr -n k8s.io i pull --hosts-dir "/etc/containerd/certs.d" "$test_img_url" \
+  if ! ctr -n k8s.io i list|grep ${test_img_url};then
+    if ! (ctr -n k8s.io i pull --hosts-dir "/etc/containerd/certs.d" "$test_img_url" \
     && ctr -n k8s.io run --rm "$test_img_url" hello-world."$(date +%s)"); then
-    utils::log "ERROR" "Could not get containerd to run ${test_img_url}"
+      utils::log "ERROR" "Could not get containerd to run ${test_img_url}"
+    fi
   fi
   return 0
 }
diff --git a/bcs-ops/k8s/install_localpv b/bcs-ops/k8s/install_localpv
--- a/bcs-ops/k8s/install_localpv
+++ b/bcs-ops/k8s/install_localpv
@@ -20,13 +20,13 @@ set -euo pipefail
 # $1: mount_dir, default /mnt/blueking
 #######################################
 
-VERSION="v2.4.0"
+LOCALPV_VER="v2.4.0"
 PROGRAM="$(basename "$0")"
 
 SELF_DIR=$(dirname "$(readlink -f "$0")")
 ROOT_DIR="${SELF_DIR}/.."
 
-readonly VERSION PROGRAM SELF_DIR ROOT_DIR
+readonly LOCALPV_VER PROGRAM SELF_DIR ROOT_DIR
 
 usage_and_exit() {
   cat <<EOF
@@ -39,7 +39,7 @@ EOF
 }
 
 version() {
-  echo "$PROGRAM version $VERSION"
+  echo "$PROGRAM version $LOCALPV_VER"
 }
 
 safe_source() {
@@ -48,7 +48,7 @@ safe_source() {
     #shellcheck source=/dev/null
     source "${source_file}"
   else
-    echo "[ERROR]: FAIL to source, missing ${source_file}"
+    echo "[ERROR]: FAIL to source, missing ${source_file}" >&2
     exit 1
   fi
 }
@@ -58,33 +58,26 @@ install_localpv() {
   kubectl get ns "$namespace" || kubectl create ns $namespace
 
   if [[ -n ${BCS_OFFLINE:-} ]]; then
-    chart_path="$(find "${ROOT_DIR}/version-${K8S_VER}/charts/" -iname "provisioner-*.tgz" -type f | head -1)"
+    chart_path="$(find "${ROOT_DIR}/charts/" -name "provisioner-${LOCALPV_VER}.tgz" -type f)"
     if [[ -z $chart_path ]]; then
       utils::log "FATAL" "can't find provisioner chart in ${ROOT_DIR}/version-${K8S_VER}/charts/"
     fi
-  else
-    [[ -n ${BKREPO_URL:-} ]] || utils::log "FAIL" "missing bkrepo url ${BKREPO_URL}"
-    if ! k8s::safe_add_helmrepo blueking "${BKREPO_URL}"; then
-      utils::log "WARNING" "something wrong with helm, skip install provisioner"
-      return 1
-    fi
-    chart_path="blueking/provisioner"
   fi
 
   local image
   if [[ -n ${BK_PUBLIC_REPO:-} ]]; then
-    image="${BK_PUBLIC_REPO}/k8s.gcr.io/sig-storage/local-volume-provisioner:${VERSION}"
+    image="${BK_PUBLIC_REPO}/k8s.gcr.io/sig-storage/local-volume-provisioner:${LOCALPV_VER}"
   else
-    image="registry.k8s.io/sig-storage/local-volume-provisioner:${VERSION}"
+    image="registry.k8s.io/sig-storage/local-volume-provisioner:${LOCALPV_VER}"
   fi
 
   utils::log "INFO" "installing localpv"
-  cat <<EOF | helm upgrade --install provisioner blueking/provisioner -n $namespace --version ${VERSION} --debug -f - || utils::log "FATAL" "helm upgrade localpv failed"
+  cat <<EOF | helm upgrade --install provisioner blueking/provisioner -n $namespace --version ${LOCALPV_VER} --debug -f - || utils::log "FATAL" "helm upgrade localpv failed"
 daemonset:
   image: ${image}
 classes:
 - name: local-storage
-  hostDir: "${LOCALPV_DIR}"
+  hostDir: "${LOCALPV_DST_DIR:-"/mnt/blueking"}"
   volumeMode: Filesystem
   storageClass:
     # create and set storage class as default
diff --git a/bcs-ops/system/get_lan_ip b/bcs-ops/system/get_lan_ip
--- a/bcs-ops/system/get_lan_ip
+++ b/bcs-ops/system/get_lan_ip
@@ -28,13 +28,18 @@ Usage:
       [ -h --help -?  show usage ]
       [ -v -V --version show script version]
       [ -4 get default route lan ipv4 addr]
-	  [ -6 get default route lan ipv6 addr]
+      [ -6 get default route lan ipv6 addr]
 EOF
   exit "$1"
 }
 
 version() {
   echo "$PROGRAM version $VERSION"
+}
+
+error() {
+  local color_code="\033[031;1m"
+  echo -e "${color_code}$*\033[0m" >&2
 }
 
 #######################################
@@ -68,15 +73,24 @@ _on_cloud() {
 }
 
 _on_baremetal() {
+  if ! ip route show | grep -q "default via"; then
+    error "fail to obtain LAN_IP, default route missing"  >&2
+    exit 2
+  fi
   LAN_IP=$(ip -4 -o route get 10/8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
   if [[ -n $LAN_IP ]]; then
     echo "$LAN_IP"
     return 0
   fi
+  error "fail to obtain LAN_IP"  >&2
   exit 1
 }
 
 _on_baremetal_v6() {
+  if ! ip -6 route show | grep -q "default via"; then
+    error "fail to obtain LAN_IPv6, default route missing"  >&2
+    exit 2
+  fi
   LAN_IPv6=$(ip -6 -o route get fd00::/8 | grep -Po '(?<=src) \K[^ ]+')
   if [[ -n $LAN_IPv6 ]]; then
     echo "$LAN_IPv6"
