fix: 错误退出时的 echo 重定向为 /dev/stderr

diff --git a/bcs-ops/k8s/operate_etcd b/bcs-ops/k8s/operate_etcd
--- a/bcs-ops/k8s/operate_etcd
+++ b/bcs-ops/k8s/operate_etcd
@@ -52,7 +52,7 @@ safe_source() {
     #shellcheck source=/dev/null
     source "${source_file}"
   else
-    echo "[ERROR]: FAIL to source, missing ${source_file}"
+    echo "[ERROR]: FAIL to source, missing ${source_file}" >&2
     exit 1
   fi
 }
@@ -186,7 +186,7 @@ new_etcd() {
   if [[ -d ${data_dir} ]];then
     utils::log "FATAL" "${data_dir} already exists"
   fi
-  
+
   cp /etc/kubernetes/manifests/etcd.yaml /tmp/etcd-"${name}".yaml
   sed -i "s|--initial-cluster=.*|--initial-cluster=${initial_cluster}|g" /tmp/etcd-"${name}".yaml
   sed -i "s|/data/bcs/lib/etcd|${data_dir}|g" /tmp/etcd-"${name}".yaml
diff --git a/bcs-ops/system/mount_localpv b/bcs-ops/system/mount_localpv
--- a/bcs-ops/system/mount_localpv
+++ b/bcs-ops/system/mount_localpv
@@ -54,7 +54,7 @@ for i in $(seq -w 1 "$LOCALPV_COUNT"); do
     utils::log "WARN" "/etc/fstab: [$src_dir] or [$dst_dir] already exists"
   else
     echo "$src_dir $dst_dir none defaults,bind 0 0" >>/etc/fstab \
-      || echo "add /etc/fstab failed"
+      || echo "add /etc/fstab failed" >&2
   fi
 done
 cat /etc/fstab
