feat: jq/yq在线安装 fix: install_k8s_tools脚本变量修正

diff --git a/bcs-ops/tools/install_jq b/bcs-ops/tools/install_jq
--- a/bcs-ops/tools/install_jq
+++ b/bcs-ops/tools/install_jq
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 #######################################
 # Tencent is pleased to support the open source community by making Blueking Container Service available.
 # Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
@@ -12,11 +11,11 @@
 # limitations under the License.
 #######################################
 
-# config O&M-related configuration
 set -euo pipefail
 
+# install jq
 SELF_DIR=$(dirname "$(readlink -f "$0")")
-ROOT_DIR=${SELF_DIR}
+ROOT_DIR="${SELF_DIR}/.."
 readonly SELF_DIR ROOT_DIR
 
 safe_source() {
@@ -30,22 +29,44 @@ safe_source() {
   fi
 }
 
-source_files=("${ROOT_DIR}/functions/utils.sh")
-for file in "${source_files[@]}"; do
-  safe_source "$file"
-done
-
-"${ROOT_DIR}"/k8s/operate_completion kubeadm kubectl helm ctr yq
-
-if [[ -n "${BKREPO_URL:-}" ]]; then
-  if command -v helm &>/dev/null; then
-    utils::log "INFO" "Add repo blueking: ${BKREPO_URL}"
-    k8s::safe_add_helmrepo blueking "${BKREPO_URL}"
-    utils::log "OK" "blueking community helm chart repo added"
+_curl_jq() {
+  local url save_file version
+  version=$1
+  url="${REPO_URL}/jq-${version}.xz"
+  save_file="/tmp/jq.xz"
+  if curl -sSfL "${url}" -o "${save_file}" -m "360"; then
+    rm -f /tmp/jq
+    unxz -dc ${save_file} >/tmp/jq
+    chmod +x /tmp/jq
+    mv /tmp/jq /usr/local/bin/jq
+    rm -f ${save_file}
   else
-    warning "helm command not found, skipping"
-    return 0
+    utils::log "ERROR" "fail to download jq"
   fi
-else
-  utils::log "WARN" "BKREPO_URL is null, skipping"
-fi
+}
+
+_offline_jq() {
+  # ToDo
+  true
+}
+
+main() {
+  local source_files
+  source_files=("${ROOT_DIR}/functions/utils.sh" "${ROOT_DIR}/env/bcs.env")
+  for file in "${source_files[@]}"; do
+    safe_source "$file"
+  done
+  jq_ver=$(awk '/jq/{gsub("\"","",$2);print $2;exit}' \
+    "${ROOT_DIR}"/env/offline-manifest.yaml)
+
+  if ! command -v jq >/dev/null; then
+    if [[ -n ${BCS_OFFLINE:-} ]]; then
+      _offline_jq
+    else
+      _curl_jq "$jq_ver"
+    fi
+  fi
+  utils::log "OK" "installed $(jq -V)"
+}
+
+main
