1.合并2944PR 2.本地有镜像时不再尝试拉取镜像

diff --git a/bcs-ops/system/get_lan_ip b/bcs-ops/system/get_lan_ip
--- a/bcs-ops/system/get_lan_ip
+++ b/bcs-ops/system/get_lan_ip
@@ -74,7 +74,7 @@ _on_cloud() {
 
 _on_baremetal() {
   if ! ip route show | grep -q "default via"; then
-    error "fail to obtain LAN_IP, default route missing"
+    error "fail to obtain LAN_IP, default route missing"  >&2
     exit 2
   fi
   LAN_IP=$(ip -4 -o route get 10/8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
@@ -82,13 +82,13 @@ _on_baremetal() {
     echo "$LAN_IP"
     return 0
   fi
-  error "fail to obtain LAN_IP"
+  error "fail to obtain LAN_IP"  >&2
   exit 1
 }
 
 _on_baremetal_v6() {
   if ! ip -6 route show | grep -q "default via"; then
-    error "fail to obtain LAN_IPv6, default route missing"
+    error "fail to obtain LAN_IPv6, default route missing"  >&2
     exit 2
   fi
   LAN_IPv6=$(ip -6 -o route get fd00::/8 | grep -Po '(?<=src) \K[^ ]+')
