fix https://github.com/TencentBlueKing/bk-bcs/issues/2967 (#2978)
* fix: #issues/2967 get_lan_ip error echo

* update sops 模板

diff --git a/bcs-ops/system/get_lan_ip b/bcs-ops/system/get_lan_ip
--- a/bcs-ops/system/get_lan_ip
+++ b/bcs-ops/system/get_lan_ip
@@ -37,6 +37,11 @@ version() {
   echo "$PROGRAM version $VERSION"
 }
 
+error() {
+  local color_code="\033[031;1m"
+  echo -e "${color_code}$*\033[0m" >&2
+}
+
 #######################################
 # get ip by cloud_api
 # Return:
@@ -68,8 +73,8 @@ _on_cloud() {
 }
 
 _on_baremetal() {
-  if ! ip route show | grep "default via"; then
-    echo "fail to obtain LAN_IP, default route missing"
+  if ! ip route show | grep -q "default via"; then
+    error "fail to obtain LAN_IP, default route missing"
     exit 2
   fi
   LAN_IP=$(ip -4 -o route get 10/8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
@@ -77,13 +82,13 @@ _on_baremetal() {
     echo "$LAN_IP"
     return 0
   fi
-  echo "fail to obtain LAN_IP"
+  error "fail to obtain LAN_IP"
   exit 1
 }
 
 _on_baremetal_v6() {
-  if ! ip -6 route show | grep "default via"; then
-    echo "fail to obtain LAN_IPv6, default route missing"
+  if ! ip -6 route show | grep -q "default via"; then
+    error "fail to obtain LAN_IPv6, default route missing"
     exit 2
   fi
   LAN_IPv6=$(ip -6 -o route get fd00::/8 | grep -Po '(?<=src) \K[^ ]+')
